// VELMORA PARIS — Data layer (products, archetypes, quiz, dictionary)

window.VELMORA = window.VELMORA || {};

VELMORA.WHATSAPP = "201142426169"; //+201142426169

VELMORA.products = [
  { id:"nuit-eternelle", image:"images/perfume-1.jpg",
    name:{ar:"ليلة أبدية",en:"Nuit Éternelle"},
    tagline:{ar:"زهور سوداء تحت ضوء القمر",en:"Black florals under moonlight"},
    notes:{ar:["ياسمين","توبيروز","عنبر"],en:["Jasmine","Tuberose","Amber"]},
    price:285, category:"floral", gender:"women", season:"winter",
    scores:{mystery:88,elegance:92,freshness:30,seduction:90,power:70,warmth:75}},
  { id:"royal-oud", image:"images/perfume-2.jpg",
    name:{ar:"عود الملوك",en:"Oud Royale"},
    tagline:{ar:"عود كمبودي نادر وعنبر دافئ",en:"Rare Cambodian oud, warm amber"},
    notes:{ar:["عود","صندل","زعفران"],en:["Oud","Sandalwood","Saffron"]},
    price:420, category:"oud", gender:"unisex", season:"winter",
    scores:{mystery:95,elegance:88,freshness:15,seduction:80,power:95,warmth:92}},
  { id:"soleil-dor", image:"images/perfume-3.jpg",
    name:{ar:"شمس الذهب",en:"Soleil d'Or"},
    tagline:{ar:"حمضيات مشمسة على الريفييرا",en:"Sunlit citrus on the Riviera"},
    notes:{ar:["برغموت","نيرولي","مسك أبيض"],en:["Bergamot","Neroli","White Musk"]},
    price:245, category:"citrus", gender:"unisex", season:"summer",
    scores:{mystery:25,elegance:75,freshness:95,seduction:50,power:45,warmth:35}},
  { id:"velmora-noir", image:"images/perfume-4.jpg",
    name:{ar:"فيلمورا نوار",en:"Velmora Noir"},
    tagline:{ar:"إصدار حصري — توقيع الدار",en:"Exclusive edition — the maison signature"},
    notes:{ar:["جلد","تبغ","فانيليا مدخنة"],en:["Leather","Tobacco","Smoky Vanilla"]},
    price:580, category:"exclusive", gender:"unisex", season:"winter",
    scores:{mystery:96,elegance:95,freshness:18,seduction:92,power:90,warmth:85}},
  { id:"rose-de-paris", image:"images/perfume-5.jpg",
    name:{ar:"وردة باريس",en:"Rose de Paris"},
    tagline:{ar:"وردة دمشقية وفلفل وردي",en:"Damask rose and pink pepper"},
    notes:{ar:["وردة دمشقية","فلفل وردي","مسك"],en:["Damask Rose","Pink Pepper","Musk"]},
    price:320, category:"floral", gender:"women", season:"all",
    scores:{mystery:55,elegance:95,freshness:60,seduction:88,power:50,warmth:65}},
  { id:"bois-sauvage", image:"images/perfume-6.jpg",
    name:{ar:"الخشب البري",en:"Bois Sauvage"},
    tagline:{ar:"خشب الأرز ومسك حيواني",en:"Cedarwood and animalic musk"},
    notes:{ar:["أرز","مسك","فيتيفر"],en:["Cedar","Musk","Vetiver"]},
    price:295, category:"oud", gender:"men", season:"winter",
    scores:{mystery:78,elegance:80,freshness:35,seduction:75,power:92,warmth:80}},
  { id:"ocean-fresh", image:"images/perfume-7.jpg",
    name:{ar:"نسيم المحيط",en:"Océan Frais"},
    tagline:{ar:"ملح بحري ونسائم نيرولي",en:"Sea salt and neroli breeze"},
    notes:{ar:["ملح بحري","نيرولي","مسك مائي"],en:["Sea Salt","Neroli","Aquatic Musk"]},
    price:260, category:"citrus", gender:"men", season:"summer",
    scores:{mystery:30,elegance:78,freshness:96,seduction:60,power:55,warmth:25}},
];

VELMORA.questions = [
  { id:"q_time", prompt:{ar:"أي وقت من اليوم يشبهك أكثر؟",en:"Which time of day feels most like you?"},
    options:[
      {id:"midnight",emoji:"🌙",label:{ar:"ما بعد منتصف الليل",en:"Past midnight"},delta:{mystery:25,seduction:15,freshness:-10},next:"q_scene_night"},
      {id:"dawn",emoji:"🌅",label:{ar:"شروق الشمس",en:"Sunrise"},delta:{freshness:25,elegance:10,mystery:-10},next:"q_scene_fresh"},
      {id:"afternoon",emoji:"☕",label:{ar:"عصر هادئ",en:"A quiet afternoon"},delta:{warmth:20,elegance:15},next:"q_scene_cozy"},
      {id:"citynight",emoji:"🌆",label:{ar:"مدينة مزدحمة ليلاً",en:"A city at night"},delta:{power:20,seduction:15,mystery:10},next:"q_scene_night"},
    ]},
  { id:"q_scene_night", prompt:{ar:"أي مشهد يجذبك أكثر؟",en:"Which scene draws you in?"},
    options:[
      {id:"luxdinner",emoji:"🥂",label:{ar:"عشاء فاخر مع موسيقى هادئة",en:"Luxury dinner with low music"},delta:{elegance:20,seduction:15}},
      {id:"rooftop",emoji:"🏙️",label:{ar:"سطح برج يطل على المدينة",en:"A rooftop above the skyline"},delta:{power:20,mystery:10}},
      {id:"speakeasy",emoji:"🥃",label:{ar:"حانة سرية في زقاق",en:"A hidden speakeasy"},delta:{mystery:25,seduction:10}},
    ]},
  { id:"q_scene_fresh", prompt:{ar:"ما الذي يوقظ حواسك في الصباح؟",en:"What wakes your senses in the morning?"},
    options:[
      {id:"sea",emoji:"🌊",label:{ar:"نسيم البحر",en:"Sea breeze"},delta:{freshness:25}},
      {id:"garden",emoji:"🌿",label:{ar:"حديقة بعد المطر",en:"A garden after rain"},delta:{freshness:18,warmth:8}},
      {id:"espresso",emoji:"☕",label:{ar:"إسبريسو حاد",en:"A sharp espresso"},delta:{power:12,warmth:10}},
    ]},
  { id:"q_scene_cozy", prompt:{ar:"ما الإحساس الذي تطارده؟",en:"Which feeling do you chase?"},
    options:[
      {id:"fireplace",emoji:"🔥",label:{ar:"موقد دافئ وكتاب",en:"Warm fireplace & a book"},delta:{warmth:25,elegance:10}},
      {id:"linen",emoji:"🛏️",label:{ar:"ملاءات كتانية ناعمة",en:"Soft linen sheets"},delta:{elegance:18,warmth:12}},
      {id:"leather",emoji:"🧥",label:{ar:"كرسي جلدي قديم",en:"An old leather chair"},delta:{mystery:15,warmth:15}},
    ]},
  { id:"q_memory", prompt:{ar:"أي رائحة مرتبطة بذكرى جميلة لديك؟",en:"Which scent ties to a beautiful memory?"},
    options:[
      {id:"rain",emoji:"🌧️",label:{ar:"المطر على التراب",en:"Rain on earth"},delta:{freshness:15,mystery:10}},
      {id:"books",emoji:"📚",label:{ar:"الكتب القديمة",en:"Old books"},delta:{elegance:15,mystery:12}},
      {id:"oud",emoji:"🪵",label:{ar:"العود يحترق",en:"Burning oud"},delta:{power:18,warmth:18,mystery:10}},
      {id:"coffee",emoji:"☕",label:{ar:"القهوة المحمصة",en:"Roasted coffee"},delta:{warmth:15,power:10}},
    ]},
  { id:"q_aura", prompt:{ar:"ما الانطباع الذي تترك في الآخرين؟",en:"What impression do you leave?"},
    options:[
      {id:"magnetic",emoji:"🧲",label:{ar:"حضور مغناطيسي صامت",en:"A silent magnetic presence"},delta:{mystery:20,seduction:15}},
      {id:"icon",emoji:"👑",label:{ar:"أيقونة لا تُنسى",en:"An unforgettable icon"},delta:{elegance:20,power:15}},
      {id:"warmth",emoji:"🌞",label:{ar:"دفء يجمع الناس",en:"Warmth that gathers people"},delta:{warmth:22,freshness:8}},
      {id:"bold",emoji:"⚡",label:{ar:"شرارة جريئة",en:"A bold spark"},delta:{power:22,seduction:10}},
    ]},
  { id:"q_season", prompt:{ar:"ما الموسم الذي يلائم روحك؟",en:"Which season suits your soul?"},
    options:[
      {id:"winter",emoji:"❄️",label:{ar:"شتاء مخملي",en:"Velvet winter"},delta:{warmth:15,mystery:10,power:8}},
      {id:"summer",emoji:"🌴",label:{ar:"صيف منعش",en:"Crisp summer"},delta:{freshness:20}},
      {id:"autumn",emoji:"🍂",label:{ar:"خريف ذهبي",en:"Golden autumn"},delta:{elegance:12,warmth:12}},
      {id:"spring",emoji:"🌸",label:{ar:"ربيع زهري",en:"Floral spring"},delta:{elegance:15,freshness:12}},
    ]},
];

VELMORA.startQuestionId = "q_time";

VELMORA.archetypes = [
  { id:"midnight_king", name:{ar:"ملك منتصف الليل",en:"The Midnight King"},
    tagline:{ar:"تحكم بدون أن تتكلم.",en:"You command without speaking."},
    description:{ar:"تحمل ثقة هادئة. الناس تشعر بحضورك قبل أن تنطق. أنت السرّ الذي يُحفظ ولا يُكشف.",en:"You carry quiet confidence. People feel your presence before your words. You are the secret kept, never told."},
    bestTime:{ar:["المساء","المناسبات الحصرية","الطقس البارد"],en:["Evening","Exclusive events","Cold weather"]},
    dna:{ar:["أخشاب داكنة","عنبر دافئ","فانيليا مدخنة"],en:["Dark Woods","Warm Amber","Smoky Vanilla"]},
    matchProductId:"velmora-noir", weights:{mystery:100,elegance:80,freshness:0,seduction:90,power:95,warmth:70}},
  { id:"silent_icon", name:{ar:"الأيقونة الصامتة",en:"The Silent Icon"},
    tagline:{ar:"الأناقة هي صوتك.",en:"Elegance is your voice."},
    description:{ar:"تتحرك بانسيابية وتترك أثراً بلا ضوضاء. أناقتك مؤسسة على التفاصيل لا على الصراخ.",en:"You move with grace and leave a trace without noise. Your elegance is built on detail, not volume."},
    bestTime:{ar:["نهاراً","اللقاءات الراقية","كل الفصول"],en:["Daytime","Refined meetings","All seasons"]},
    dna:{ar:["وردة دمشقية","فلفل وردي","مسك أبيض"],en:["Damask Rose","Pink Pepper","White Musk"]},
    matchProductId:"rose-de-paris", weights:{mystery:50,elegance:100,freshness:60,seduction:80,power:50,warmth:60}},
  { id:"velvet_rebel", name:{ar:"المتمرد المخملي",en:"The Velvet Rebel"},
    tagline:{ar:"تكسر القواعد بأناقة.",en:"You break rules with elegance."},
    description:{ar:"تجمع الجرأة بالفخامة. لا تتبع موضة، أنت تصنعها.",en:"You blend daring with luxury. You don't follow trends — you set them."},
    bestTime:{ar:["الليل","الحفلات الخاصة"],en:["Night","Private parties"]},
    dna:{ar:["جلد","تبغ","عود"],en:["Leather","Tobacco","Oud"]},
    matchProductId:"royal-oud", weights:{mystery:80,elegance:70,freshness:10,seduction:75,power:95,warmth:85}},
  { id:"golden_aura", name:{ar:"الهالة الذهبية",en:"The Golden Aura"},
    tagline:{ar:"تشرق أينما ذهبت.",en:"You glow wherever you go."},
    description:{ar:"دفء يجذب الناس إليك. ابتسامتك أوسع من غرفة، وحضورك أدفأ من شتاء.",en:"A warmth that pulls people in. Your smile is wider than a room and warmer than winter."},
    bestTime:{ar:["الصباح","المساء الدافئ"],en:["Mornings","Warm evenings"]},
    dna:{ar:["ياسمين","توبيروز","عنبر"],en:["Jasmine","Tuberose","Amber"]},
    matchProductId:"nuit-eternelle", weights:{mystery:50,elegance:85,freshness:40,seduction:85,power:60,warmth:95}},
  { id:"ocean_spirit", name:{ar:"روح المحيط",en:"The Ocean Spirit"},
    tagline:{ar:"حر، منعش، لا يُقيَّد.",en:"Free, fresh, unbound."},
    description:{ar:"أنت النسيم الذي يغير المزاج. الانتعاش بطبعك والحرية لغتك.",en:"You are the breeze that shifts a mood. Freshness is your nature, freedom your language."},
    bestTime:{ar:["نهاراً","الصيف","السفر"],en:["Daytime","Summer","Travel"]},
    dna:{ar:["ملح بحري","نيرولي","مسك مائي"],en:["Sea Salt","Neroli","Aquatic Musk"]},
    matchProductId:"ocean-fresh", weights:{mystery:25,elegance:70,freshness:100,seduction:55,power:50,warmth:30}},
  { id:"sunlit_muse", name:{ar:"ملهمة الشمس",en:"The Sunlit Muse"},
    tagline:{ar:"خفّة تترك أثراً.",en:"A lightness that lingers."},
    description:{ar:"تجعل العالم يبدو أخف وأكثر إشراقاً. ذوقك حمضي مشرق ولا يتقادم.",en:"You make the world feel lighter and brighter. Your taste is citrus-bright and timeless."},
    bestTime:{ar:["النهار","الإجازات","الصيف"],en:["Day","Holidays","Summer"]},
    dna:{ar:["برغموت","نيرولي","مسك أبيض"],en:["Bergamot","Neroli","White Musk"]},
    matchProductId:"soleil-dor", weights:{mystery:20,elegance:75,freshness:95,seduction:50,power:45,warmth:35}},
  { id:"wildwood", name:{ar:"روح الغابة",en:"The Wildwood Soul"},
    tagline:{ar:"بدائي بأناقة.",en:"Primal, elegantly."},
    description:{ar:"أنت الغموض الخشبي. هادئ من بعيد، قوي من قريب.",en:"You are woody mystery. Calm from afar, powerful up close."},
    bestTime:{ar:["الشتاء","الليل","الأماكن المفتوحة"],en:["Winter","Night","Outdoors"]},
    dna:{ar:["أرز","مسك","فيتيفر"],en:["Cedar","Musk","Vetiver"]},
    matchProductId:"bois-sauvage", weights:{mystery:80,elegance:75,freshness:35,seduction:70,power:90,warmth:80}},
];

VELMORA.dict = {
  nav_home:{ar:"الرئيسية",en:"Home"},
  nav_collections:{ar:"المجموعات",en:"Collections"},
  nav_story:{ar:"قصتنا",en:"Our Story"},
  nav_quiz:{ar:"اكتشف عطرك",en:"Discover Your Scent"},
  nav_bespoke:{ar:"عطر مخصص",en:"Bespoke"},
  nav_journal:{ar:"المجلة",en:"Journal"},
  nav_contact:{ar:"تواصل",en:"Contact"},
  hero_tag:{ar:"جوهر الفخامة",en:"Essence of Luxury"},
  hero_sub:{ar:"دار عطور حصرية — رسائل حب مصاغة من قلب مصر.",en:"An exclusive maison of perfumes — love letters crafted from Egypt heart."},
  hero_cta:{ar:"اكتشف المجموعة",en:"Discover Collection"},
  hero_cta2:{ar:"حلل شخصيتك العطرية",en:"Take the Scent Quiz"},
  coll_title:{ar:"العطور المميزة",en:"Signature Fragrances"},
  coll_sub:{ar:"دار مختارة من سبعة عطور حصرية — كل واحد قصة حب من مصر.",en:"A curated maison of seven extraits — each one a love letter from Egypt."},
  filter_all:{ar:"الكل",en:"All"}, filter_floral:{ar:"زهري",en:"Floral"},
  filter_oud:{ar:"عود",en:"Oud"}, filter_citrus:{ar:"حمضي",en:"Citrus"},
  filter_exclusive:{ar:"حصري",en:"Exclusive"}, filter_women:{ar:"نسائي",en:"Women"},
  filter_men:{ar:"رجالي",en:"Men"}, filter_summer:{ar:"صيفي",en:"Summer"},
  filter_winter:{ar:"شتوي",en:"Winter"},
  add_to_cart:{ar:"أضف إلى السلة",en:"Add to Cart"},
  notes:{ar:"نوتات العطر",en:"Fragrance Notes"},
  oils_title:{ar:"الزيوت العطرية",en:"Aromatic Oils"},
  oils_sub:{ar:"تشكيلة جديدة من الزيوت النقية الفاخرة — قريباً.",en:"A new collection of pure luxurious oils — coming soon."},
  coming_soon:{ar:"قريباً",en:"Coming Soon"},
  notify_me:{ar:"أبلغني عند التوفر",en:"Notify Me"},
  story_title:{ar:"إرث من مصر",en:"A Heritage from Egypt"},
  story_p1:{ar:"ولدت فيلمورا نيش بيرفيوم في قلب مصر، حيث تلتقي الحرفية المصرية بأرقى المكونات. كل عطر هو حكاية، وكل قطرة هي توقيع.",en:"VELMORA Nich Perfume was born in the heart of Egypt, where Egyptian craftsmanship meets the finest ingredients. Each fragrance is a story, each drop a signature."},
  quiz_title:{ar:"اكتشف هويتك العطرية",en:"Discover Your Scent Identity"},
  quiz_sub:{ar:"محرك تحليل شخصي متقدم — أجب بصدق وسنكشف عن DNA العطر الذي يشبهك.",en:"An advanced personality engine — answer honestly and we will decode your fragrance DNA."},
  quiz_start:{ar:"ابدأ التحليل",en:"Begin Analysis"},
  quiz_back:{ar:"السابق",en:"Back"},
  quiz_decoding:{ar:"جارٍ فك شفرة هويتك العطرية…",en:"Decoding your fragrance identity…"},
  quiz_your_id:{ar:"أنت",en:"You Are"},
  quiz_dna:{ar:"DNA العطر المثالي لك",en:"Your Ideal Fragrance DNA"},
  quiz_best_time:{ar:"أفضل وقت للارتداء",en:"Best Time To Wear"},
  quiz_recommended:{ar:"العطر الموصى به",en:"Your Match"},
  quiz_retake:{ar:"إعادة التحليل",en:"Retake"},
  quiz_shop:{ar:"اشترِ الآن",en:"Shop Now"},
  quiz_share:{ar:"شارك نتيجتك",en:"Share Your Result"},
  cart:{ar:"السلة",en:"Cart"},
  cart_empty:{ar:"السلة فارغة",en:"Your cart is empty"},
  cart_subtotal:{ar:"الإجمالي",en:"Subtotal"},
  cart_checkout:{ar:"إتمام الطلب",en:"Checkout"},
  co_title:{ar:"تأكيد الطلب",en:"Confirm Your Order"},
  co_sub:{ar:"أدخل بياناتك وسنرسل الطلب مباشرة عبر واتساب.",en:"Enter your details and we'll send the order via WhatsApp."},
  co_name:{ar:"الاسم الكامل",en:"Full Name"},
  co_phone:{ar:"رقم الهاتف الأساسي",en:"Primary Phone"},
  co_phone2:{ar:"رقم هاتف إضافي (اختياري)",en:"Secondary Phone (optional)"},
  co_address:{ar:"العنوان بالتفصيل",en:"Full Address"},
  co_city:{ar:"المدينة",en:"City"},
  co_notes:{ar:"ملاحظات (اختياري)",en:"Notes (optional)"},
  co_send:{ar:"إرسال الطلب عبر واتساب",en:"Send Order via WhatsApp"},
  newsletter_title:{ar:"انضم إلى قصر العطور",en:"Join the Maison"},
  newsletter_sub:{ar:"أخبار حصرية وإطلاقات محدودة.",en:"Exclusive news and limited drops."},
  newsletter_btn:{ar:"اشتراك",en:"Subscribe"},
  email_ph:{ar:"بريدك الإلكتروني",en:"Your email"},
  journal_title:{ar:"المجلة",en:"Journal"},
  bespoke_title:{ar:"العطر المخصص",en:"Bespoke Perfume"},
  bespoke_sub:{ar:"احجز استشارة لصياغة عطرك الفريد.",en:"Book a consultation to craft your unique scent."},
  bespoke_btn:{ar:"احجز استشارة",en:"Book Consultation"},
  rights:{ar:"© 2026 فيلمورا نيش بيرفيوم. جميع الحقوق محفوظة.",en:"© 2026 Velmora Nich Perfume. All rights reserved."},
  added_toast:{ar:"أُضيف إلى السلة",en:"Added to cart"},
  remove:{ar:"إزالة",en:"Remove"},
  contact_title:{ar:"تواصل معنا",en:"Contact Us"},
  contact_sub:{ar:"نسعد بالرد على استفساراتك عبر واتساب.",en:"We are delighted to answer you via WhatsApp."},
  contact_btn:{ar:"محادثة واتساب",en:"WhatsApp Chat"},
  scoreL_mystery:{ar:"الغموض",en:"Mystery"},
  scoreL_elegance:{ar:"الأناقة",en:"Elegance"},
  scoreL_freshness:{ar:"الانتعاش",en:"Freshness"},
  scoreL_seduction:{ar:"الإغواء",en:"Seduction"},
  scoreL_power:{ar:"القوة",en:"Power"},
  scoreL_warmth:{ar:"الدفء",en:"Warmth"},
};
